### PR TITLE
Add summary at the end of all run tests

### PR DESCRIPTION
**Pull request by fnogatz**
Output as comments, similar to https://www.npmjs.com/package/tape#example.

### CODE REVIEW

**Comment by mndrix** [comment]
These changes look sensible.  I'm no longer using this library and was about to archive it on GitHub.  Would you be interested in taking over maintenance?  If so, I'll transfer ownership of this repository to you.  Then you can merge the pull request and release a new pack.

**Comment by fnogatz** [comment]
Probably I'm the most active user of `library(tap)`, so I would like to take over the project.

**Comment by mndrix** [comment]
I tried the transfer a couple different ways, but GitHub keeps complaining because you already have a fork of this same repository.  It looks like we have two options:

  * you can delete your tap repository and I can transfer this one to you
  * I can archive this repository and update the README to point at your repo

The second one seems easier, but I'll do whatever you want since you'll be the new maintainer.

**Comment by fnogatz** [comment]
Hi Michael,

> you can delete your tap repository and I can transfer this one to you

I just did this. I was wondering what would happen with this PR, but apparently GitHub did not crash :angel:

**Comment by mndrix** [comment]
I initiated the transfer. Thanks for being willing to maintain this project.

**Pull request merged**
